# Generated by Django 4.2.16 on 2024-12-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("bkash", "bKash")], max_length=20
            ),
        ),
    ]
