# Generated by Django 4.2.16 on 2024-12-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_event_available_normal_tickets_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="available_vip_tickets",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
